### ISSUE TITLE
add Zenodo DOI for citations?

### ISSUE THREAD

**Issue by davedgd** [singmann/monet#2]
@singmann: Thank you for providing this convenient package (which I found via an old [R-sig-ME discussion](https://stat.ethz.ch/pipermail/r-sig-mixed-models/2018q3/027106.html) you had with Guillaume)!

Regarding this package, I imagine you're not planning on releasing this on CRAN any time soon given it hasn't been updated in a while, but I was wondering if you'd consider creating a citable DOI via [Zenodo](https://guides.github.com/activities/citable-code/) so we can reference it more easily in research?

Thanks again Henrik!

**Comment by singmann** [comment]
Thanks for the idea and glad to know this package is of use to you. I have tried to create a zenodo doi. It should be here: https://zenodo.org/record/4697305

I have also added it to the README. Please let me know if this is enough.

**Comment by davedgd** [comment]
@singmann: This is perfect -- thanks for providing an easier way to cite your work! =)
